// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3ELkfUIbZo-WnKkdQlNC2iCtLjCX1dn8',
    appId: '1:24090768597:web:5b2b3b1f3a5e665e491e5c',
    messagingSenderId: '24090768597',
    projectId: 'tourmate-040',
    authDomain: 'tourmate-040.firebaseapp.com',
    storageBucket: 'tourmate-040.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBXugLgGnrBHdqsZxcjh-oLYOAroFcUq0',
    appId: '1:24090768597:android:dde0fd7a76f92691491e5c',
    messagingSenderId: '24090768597',
    projectId: 'tourmate-040',
    storageBucket: 'tourmate-040.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDLpZ6E3d9YVERRP-rGh58HdXpQngZSgM',
    appId: '1:24090768597:ios:ad25201cfef99b45491e5c',
    messagingSenderId: '24090768597',
    projectId: 'tourmate-040',
    storageBucket: 'tourmate-040.firebasestorage.app',
    iosBundleId: 'com.example.tourmateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDLpZ6E3d9YVERRP-rGh58HdXpQngZSgM',
    appId: '1:24090768597:ios:ad25201cfef99b45491e5c',
    messagingSenderId: '24090768597',
    projectId: 'tourmate-040',
    storageBucket: 'tourmate-040.firebasestorage.app',
    iosBundleId: 'com.example.tourmateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3ELkfUIbZo-WnKkdQlNC2iCtLjCX1dn8',
    appId: '1:24090768597:web:ea6b105c5b86cd47491e5c',
    messagingSenderId: '24090768597',
    projectId: 'tourmate-040',
    authDomain: 'tourmate-040.firebaseapp.com',
    storageBucket: 'tourmate-040.firebasestorage.app',
  );
}
